name: macOS CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

env:
  BUILD_TYPE: RelWithDebInfo
  TEMP: ${{github.workspace}}/temp/

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Downloading a DLS file for testing'
      uses: ethanjli/cached-download-action@6bee1d546f48427140e81ed759b343229c93b7c5
      with:
        url: http://www.ronimusic.com/sf2/Airfont_340.dls
        destination: temp/soundfont.dls
        cache-key: alt.soundfont.dls
        enable-cross-os-archive: true

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}} -VV
