name: Windows MSYS2 CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

env:
  BUILD_TYPE: RelWithDebInfo

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}

    steps:
    - uses: actions/checkout@v4

    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        release: false
        msystem: MINGW64
        install: >-
          make
        pacboy: >-
          toolchain:p
          cmake:p
          ninja:p

    - name: Downloading a DLS file for testing'
      uses: ethanjli/cached-download-action@v0.1.3
      with:
        url: http://www.ronimusic.com/sf2/Airfont_340.dls
        destination: temp/soundfont.dls
        cache-key: alt.soundfont.dls
        enable-cross-os-archive: true

    - name: 'Copy soundfont to TEMP'
      run: |
        cp temp/soundfont.dls $TEMP

    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -G Ninja

    - name: Build
      run: cmake --build build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: build
      run: ctest -C ${{env.BUILD_TYPE}} -VV

